USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_NAME_MAX_LENGTH = 150
USER_AVATAR_UPLOAD_TO = 'avatars/'

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 128
RECIPE_IMAGE_UPLOAD_TO = "recipes/"

MAX_IMAGE_SIZE = 5 * 1024 * 1024
COOKING_MIN_VALUE = 1

PAGINATION_PAGE_SIZE = 6
PAGINATION_MAX_PAGE_SIZE = 50
DOWNLOAD_SHOPPING_CART_FILE_NAME = "shopping_list.txt"
